spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: SubjectRevice
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/**
        - id: Oder
          uri: http://localhost:8084
          predicates:
            - Path=/api/v2/**
